### PR TITLE
Added New Hair style Raine

### PR DESCRIPTION
**Pull request by FishStix4Dayz**
I created a new Vulpkanin hairstyle called raine. It works fine i've tested it and everything.
🆑:
add : Raine hairstyle for vulpkanin.
/🆑

image

### CODE REVIEW

**Comment by cebutris** [comment]
Why is this vulpkanin specific? Why can't it be for other races?

**Comment by FishStix4Dayz** [comment]
because thats what i programmed and designed it for

**Comment by FishStix4Dayz** [comment]
So i have to go back and remodel for about 67 different species and program all of them, thats what your telling me?

**Comment by thingpony** [comment]
They have almost all the same heads. Simply make it free for all races to use, it shouldn't be more than a few pieces of code, like the other hair styles.

**Comment by Tk420634** [comment]
Who even are you, btw?  A lurker?  Say hey on the Discord sometime, lol.

**Pull request merged**
