### PR TITLE
im back, kinda

### PR DESCRIPTION
**Pull request by AnonymousHybi**
i cant remember what i done.

### CODE REVIEW

**Comment by Tk420634** [comment]
**All checks have failed!**

**Comment by Tk420634** [comment]
Jon, is this mess safe to merge? :V

**Comment by jonathanhybrid** [comment]
The command "source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup" exited with 0.
136.68s$ bash dm.sh -M${DM_MAPFILE} paradise.dme
DM compiler version 511.1380
loading paradise.mdme
loading interface/skin.dmf
code/dallus_content/machines/vending.dm:276:error: /obj/item/clothing/under/birthdaysuit: undefined type path
paradise.mdme.dmb - 1 error, 0 warnings (12/13/17 12:26 am)
mv: cannot stat ‘paradise.mdme.dmb’: No such file or directory

**Comment by jonathanhybrid** [comment]
code/dallus_content/machines/vending.dm:276:error: /obj/item/clothing/under/birthdaysuit: undefined type path

once again someone forgot to define a birthdaysuit.

**Comment by Tk420634** [comment]
The birthday suit thats in game, and works perfectly right now? :^)

**Comment by jonathanhybrid** [comment]
then get the directory and change it in vending.dm

**Comment by jonathanhybrid** [comment]
cause obviously there's an error, as you can see.

**Comment by AnonymousHybi** [comment]
Should be good, i'll let travis do a check real quick first tho.

**Comment by Tk420634** [comment]
:eyes:

**Pull request merged**
