### PR TITLE
Fixed Brig Physician access

### PR DESCRIPTION
**Pull request by Hibou48888**
Added the following areas to the BP's list: Brig, Court, Security, Maintenance. They now match the security officer's clearance, save for weapons. (And the medical stuff, of course.)

### CODE REVIEW

**Comment by Hibou48888** [comment]
So I clean compiled this on my local machine and it didn't come through with any errors. The only thing I can think of is maybe one of the access levels I gave the BP doesn't exist on the map that it compiled, but that would be kinda weird if that actually caused an issue that resulted in a timeout and not an explicit build error. Maybe someone else has some other ideas?

**Comment by Tk420634** [comment]
Hey Hibbles.  I know it's a bit late, but can you double check this, I've been so busy lately it's a miracle I've had time to breath.  Lemme know if it works, and I'll merge it.  Sorry fam. :v

**Comment by Tk420634** [comment]
👀 Cebu redid this, sorry Hibiwibi.

**Comment by cebutris** [comment]
Except no I didn't! Brig Physician is totally different than a Paramedic!

**Pull request closed without merging**
