### PR TITLE
blacklists some nullrod variants

### PR DESCRIPTION
**Pull request by cebutris**
Most of the swords and all of the nodrop variants of the nullrod have been removed.

### CODE REVIEW

**Comment by Tk420634** [comment]
Is this good or what?

**Comment by cebutris** [comment]
I'm 90% sure this is good but I have been wrong before. It works on my end.

**Comment by cebutris** [comment]
Bump

**Comment by Tk420634** [comment]
Lemme readd the rod, then I'll merge dis cebubbles.  Sorrrryyyy

**Pull request merged**
