### PR TITLE
Hotfix Bundle 9000++

### PR DESCRIPTION
**Pull request by TalkingCactus**
### Bugfix list
- [x] Aliens hear everyone as "unknown" over radio and are heard as "alien" instead of their actual name.
- [x] Aliens talking through a radio no longer play several voice sounds.
- [x] Fixed alien x/y offsets being incorrect while riding vehicles.
- [x] Fixed aliens clicking an open door on help intent and having nothing happen.
- [x] Aliens now have their nightvision HUD back so they can click it to toggle nightvision. Also snuck in some missing UI bits for them.
~~Plasma cutters are no longer shit.~~
~~Video cameras should work as expected now.~~
- [x] Fixed jolteons not charging power cells used on them. Also cleaned up their code a bit so they're less buggy and more informative.
- [x] Fixed some mapping issues in the garden.
- [x] Fixed some typos.
- [x] Fixed the shower in the cloning room.
### Feature list
- Added a pet to Engineering.
- Added some presets for admin aliens, as requested.
- Added the plant bag of holding.
- Got bored and added a fire cape.
- Added a secure containment cell to the Xenobiology Lab.
- All (most) alien abilities converted to action buttons.
- Some more stuff, but I forgot.

### CODE REVIEW

**Comment by jonathanhybrid** [comment]
Is there anyway I can send a commit to you? Or do you pull my work into this PR?

**Comment by TalkingCactus** [comment]
Maintainers can edit the branch.

**Comment by jonathanhybrid** [comment]
Not a maintainer. Also could it be the Bump() proc on the projectile?

**Comment by TalkingCactus** [comment]
I've speculated that it may have something to do with the turf not being deleted before it bumps into it again.

**Comment by jonathanhybrid** [comment]
`/obj/item/projectile/Bump(atom/A, yes)
	if(!yes) //prevents double bumps.
		return
	if(firer)
		if(A == firer || (A == firer.loc && istype(A, /obj/mecha))) //cannot shoot yourself or your mech
			loc = A.loc
			return 0

	var/distance = get_dist(get_turf(A), starting) // Get the distance between the turf shot from and the mob we hit and use that for the calculations.
	def_zone = ran_zone(def_zone, max(100-(7*distance), 5)) //Lower accurancy/longer range tradeoff. 7 is a balanced number to use.

	if(isturf(A) && hitsound_wall)
		var/volume = Clamp(vol_by_damage() + 20, 0, 100)
		if(suppressed)
			volume = 5
		playsound(loc, hitsound_wall, volume, 1, -1)
	else if(ishuman(A))
		var/mob/living/carbon/human/H = A
		var/obj/item/organ/external/organ = H.get_organ(check_zone(def_zone))
		if(isnull(organ))
			return

	var/turf/target_turf = get_turf(A)

	var/permutation = A.bullet_act(src, def_zone) // searches for return value, could be deleted after run so check A isn't null
	if(permutation == -1 || forcedodge)// the bullet passes through a dense object!
		loc = target_turf
		if(A)
			permutated.Add(A)
		return 0
	else
		if(A && A.density && !ismob(A) && !(A.flags & ON_BORDER)) //if we hit a dense non-border obj or dense turf then we also hit one of the mobs on that tile.
			var/list/mobs_list = list()
			for(var/mob/living/L in target_turf)
				mobs_list += L
			if(mobs_list.len)
				var/mob/living/picked_mob = pick(mobs_list)
				picked_mob.bullet_act(src, def_zone)
	qdel(src)`

**Comment by jonathanhybrid** [comment]
UHM. Anyway, bottom of this proc is "qdel(src)"

**Pull request merged**
