### PR TITLE
whoops

### PR DESCRIPTION
**Pull request by thingpony**
Fixed a whoopsie on the map

### CODE REVIEW

**Comment by TalkingCactus** [comment]
what did you actually change though

**Comment by TalkingCactus** [comment]
if it's affecting gameplay you need to update the changelog, too

**Comment by thingpony** [comment]
Nah its not, its just fixing a missing floor tile

**Comment by TalkingCactus** [comment]
where

**Comment by TalkingCactus** [comment]
we need the bar stools fixed, too. bundle them with this

**Comment by thingpony** [comment]
I already fixed the bar stools

**Pull request merged**
