### PR TITLE
turbin

### PR DESCRIPTION
**Pull request by TalkingCactus**
Makes the turbine a competitive option for power production at the cost of a small fraction of the oxygen and plasma storage tanks.

Power ratings are as follows:

- Stock parts: ~100KW
- Fully Upgraded: ~450-600KW

I may need to do some post-merge tweaks to keep the power production at a suitable level.
turbin
(screenshot is slightly out of date but that's roughly what you'll see in game)

### CODE REVIEW

**Comment by TalkingCactus** [comment]
fix travis @AnonymousHybi

**Comment by Tk420634** [comment]
Cactus what am I doing with this?

**Comment by TalkingCactus** [comment]
it works, travis is just fudge. you can merge

**Comment by Tk420634** [comment]
:eyes:

**Pull request merged**
